months = {
"1" : "Jan - \nJanuary people are hard-working and know how to get the job done.\nThey are neat, organized and serious when needed, which makes them great leaders in the business world.\nWhile they can be critical, they are also sensitive and have a hard time expressing their emotions.\nThey can also be stubborn and hard to please.\nPeople born in January tend to love children and have very loyal romantic partners\nwho are very attentive and have deep emotions.",
"2" : "Feb \nPeople born in February are the free spirits of the calendar year as they frequently have a changing personality that can be temperamental one minute and quiet and shy the next.\nMany are deep thinkers who love to explore new goals and dreams and take daring risks to reach their ambitions.\nSome suffer from superstition and odd ideas about the world.\nMany February people are attractive and charming and easily make friends,\nalthough they are not prone to showing romantic love very openly.",
"3" : "March \nThese sensitive folk can be very sympathetic to others and love to take care of them and to create a feeling of serene peacefulness.\nThey are affectionate and attractive, but also can be reserved in their outward expressions.\nPeople born in March will always return a kindness and can easily see when others need some help or emotional boosting.\nThey are honest and trustworthy and love attention.\nUnfortunately,these people can also hold grudges and can be moody when not in a serene place.",
"4" : "April \nWhile people born in April may not be traditionally attractive or enticing, their strong personality and love of attention can make them fun friends.\nThey are highly active and sometimes act too hastily when seeking new adventure.\nThey are great motivators, but can be aggressive and too emotional for some people to handle.\nThey tend to have good memories, are great diplomats and can assist friends and family with solutions to their problems.",
"5" : "May \nA-type personalities have tons of motivation and a quick intellect to get any job done.\nThey are generally attractive both physically and mentally and attract strong partners.\nThese restless people love travelling, they take part in the arts and get involved in groups where their skills can be appreciated by others.",
"6" : "June \nIndividuals born in June tend to be sensitive.\nWhile they easily make friends with their politeness and good sense of humor, they can be temperamental and are deeply affected when hurt. \nOften talkative, they enjoy debating and getting into deep conversations where they can exercise their active minds.",
"7" : "July \nVery approachable and friendly.\nThese are sparkling personalities that attract people easily.\nThey protect their reputation for being honest and caring about other people’s feelings.\nMoodiness at times can form a barrier between them and others.\nThey are generally quiet unless provoked, and then can hold a grudge for a long time.\nMany of them have digestive or weight problems they need to overcome.\nThey tend to work hard and often do well in learning.",
"8" : "August \nGreat leaders are often born in August.\nThey have a fearless personality with great ability to lead others to a goal.\nOften attractive and suave, they love to be the center of attention and enjoy compliments from others.\nThey are highly romantic and show their affections easily.\nHowever, when something goes wrong in a relationship they act hastily and can let their pride in themselves cause excessive anger and jealousy.\nAugust people can be highly generous, have great dreams for themselves and have artistic and musical talent.",
"9" : "September \nThese are stubborn people.\nThey are confident in their own abilities, hard-working and very organized.\nAlthough they may point out negative aspects of other people, they are quite intelligent and love to seek out new information.\nSometimes, September people can seem unemotional since they tend to hold their feelings inside.",
"10" : " oct \nPeople born in October love to make friends and are good at it.\nThey return affection to those who give it to them easily, and treat their friends and loved ones with great importance.\nA conversation with an October person can be filled with jokes, dreams and strong opinions.\nThey tend not to focus on others’ impressions of them and recover quickly from any slights.\nAlthough they may lie and be jealous at times, people born in October are mostly fair, friendly and usually love children.",
"11" : "Nov \nThese tough November people have a lot of ideas about different projects, the future, work and other people too.\nSometimes secretive, they can be too quiet in a group setting, hardhearted, unpredictable and quick to anger.\nIf they can overcome the negative aspects of their personality, others can share with them a very deep and abiding love, plenty of romance and very strong friendships.\nThey are honest and trustworthy in all dealings with others.",
"12" : "Dec \nDecember people are active, playful, have great sense of humor and frequently patriotic.\nSome negative traits include a short temper, impatience, acting too hastily and looking at things very logically.\nIf December people want to be loved and praised, they should temper their negative traits.",
}

real_name = input('welcome please what is your Nickname ?')
print("Are you curious about what your Birth Month say about your personality ?")
print("Enter your month of birth in Number and the program will do the rest" + real_name)
print()
name = input("what is your month in numbers ? ")
if name in months:
  name = months[name]
  print(name)
else:
    print("Invalid entry, Try again")
